/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import static hexlet.code.Cli.greetUser;

public class App {
    public static void main(String[] args) {
        greetUser();
    }
}
